services:
  db:
    image: postgres:16-alpine
    container_name: want-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: want
      POSTGRES_USER: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./want-back
    container_name: want-back
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/want?currentSchema=private
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ""
      WANT_CORS_ALLOWEDORIGINS: http://localhost:5173 #FE

  frontend:
    image: node:20-alpine
    container_name: want-front
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
