spring.datasource.url=jdbc:postgresql://localhost:5432/banyan?currentSchema=want_app
spring.jpa.properties.hibernate.default_schema=want_app

spring.datasource.username=banyan_dml # app user
spring.datasource.password=Leobest9

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
want.cors.allowedOrigins=https://banyan.readresolve.tech
# api-1, api-2, api-3
# 60133, 60134, 60135