spring.datasource.url=jdbc:postgresql://localhost:5432/want?currentSchema=private
spring.jpa.properties.hibernate.default_schema=private

spring.datasource.username=admin
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
