spring.application.name=want-${spring.profiles.active}

# JWT 'real' secret: 
want.jwt.secret=secretKey123agdksfnjsbdjnkmflew32sdsdajivjkdmlabsfjndklms

#JWT expiration in seconds, set to -1 for no expiration: (1h)
want.jwt.expiration=3600


# admin + private -> dev/test
# app_user + public -> prod