DROP TABLE IF EXISTS private.t_review_likes CASCADE;
DROP TABLE IF EXISTS private.t_reviews CASCADE;
DROP TABLE IF EXISTS private.t_users CASCADE;

-- private
CREATE TABLE private.t_users (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(60) NOT NULL
);

CREATE TABLE private.t_reviews (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  osm_id BIGINT NOT NULL,
  user_id INTEGER REFERENCES private.t_users(id) ON DELETE SET NULL,  
  comment VARCHAR(500) NOT NULL,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  amenity VARCHAR(7) NOT NULL,
  time_stamp TIMESTAMP WITH TIME ZONE NOT NULL,
  like_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE private.t_review_likes (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY key,
  review_id INTEGER NOT NULL REFERENCES t_reviews(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES t_users(id) ON DELETE SET NULL,
  UNIQUE (review_id, user_id)
);
