DROP TABLE IF EXISTS t_accounts CASCADE;
DROP TABLE IF EXISTS t_reviews CASCADE;
DROP TABLE IF EXISTS t_review_likes CASCADE;

CREATE TABLE t_accounts (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(60) NOT NULL
);

CREATE TABLE t_reviews (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   osm_id BIGINT NOT NULL,
  publisher VARCHAR(100)
    REFERENCES t_accounts(email) 
    ON DELETE SET NULL,
  comment VARCHAR(500) NOT NULL,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  amenity VARCHAR(7) NOT NULL,
  lon DOUBLE PRECISION NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  time_stamp TIMESTAMP WITH TIME ZONE NOT null,
  like_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE t_review_likes (
  id SERIAL PRIMARY KEY,
  review_id BIGINT NOT NULL REFERENCES t_reviews(id) ON DELETE CASCADE,
  user_email VARCHAR(100) NOT NULL,
  UNIQUE (review_id, user_email) -- non autorized : duplicate review_id + user_email 
);

